{
  log.debug("Exception caught {}",cause);
}
